### ISSUE TITLE
You must supply options.name for IIFE bundles

### ISSUE THREAD

**Issue by aubergene** [ko-yelie/gulp-rollup-each#7]
I get this error when trying to compile. I can specify the name as a string, but I need it to be a function. Ideally by default it would just be the name of the file.

```
Message:
    You must supply options.name for IIFE bundles
Details:
    code: INVALID_OPTION
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```
